version: "3.8"
services:
  #MongoDB
  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
      AUTH: admin
    ports:
      - "27017:27017"
    volumes:
      - "my_mongodb_data:/data/db"

    #Mongo Express
  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
      ME_CONFIG_MONGODB_SERVER: mongoDB
    ports:
      - "8081:8081"
    depends_on:
      - mongoDB

volumes:
  my_mongodb_data:
    driver: local
