
PATCH http://localhost:4000/api/v2/articles/6504a114b595d080994b8210
content-Type: application/json


[
     {
    "op": "replace",
    "path": "title",
    "value": "json patch updated"
  },
  {
    "op": "replace",
    "path": "body",
    "value": "Updated body using json patch"
  },
  {
    "op": "add",
    "path": "test",
    "value": "test property"
  },{
    "op": "remove",
    "path": "cover"
  }
 
]

####

POST http://localhost:4000/api/v1/auth/signup
content-Type: application/json

{
    "name":"test",
    "email":"test@test.com",
    "password":"test"
}